#   Configure file for pyKlock.py 
#   (c) Kevin Scott   Written Sunday 02 November 2025  20:36:56
#
#   true and false are lower case 
#
[INFO]
myVERSION = "2025.7"
myNAME = "pyKlock"

[APPLICATION]
x_pos = 7
y_pos = 160
width = 842
height = 187
confirmExit = false

[DISPLAY]
foreground = "#00ff00"
background = "#000000"

[TIME]
mode = "Text"
format = "Fuzzy Time"
font = "Palace Script MT,72,-1,5,400,1,0,0,0,0,0,0,0,0,0,1,Regular"
