#   Configure file for pyKlock.py 
#   (c) Kevin Scott   Written Wednesday 10 December 2025  15:42:48
#
#   true and false are lower case 
#
[INFO]
myVERSION = "2025.11"
myNAME = "pyKlock"

[APPLICATION]
x_pos = 2484
y_pos = 74
width = 920
height = 189
confirmExit = false

[DISPLAY]
foreground = "#ffff7f"
background = "#000000"
transparent = true

[TIME]
mode = "Text"
format = "Fuzzy Time"
font = "Edwardian Script ITC,72,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,Regular"
