#   Configure file for pyKlock.py 
#   (c) Kevin Scott   Written Monday 09 February 2026  21:48:37
#
#   true and false are lower case 
#
[INFO]
myVERSION = "2026.41"
myNAME = "pyKlock"

[APPLICATION]
x_pos = 2809
y_pos = 27
width = 581
height = 63
confirmExit = false
menu = true
toolBar = false
menuBar = true

[DISPLAY]
foreground = "#00ff00"
background = "#000000"
transparent = true
infoLine = true

[TIME]
mode = "Text"
format = "Fuzzy Time"
font = "Curlz MT,36,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,Regular"
alignment = "Right"
prefix = ""
postfix = ""
space = " "

[SOUNDS]
sounds = true
westminster = true
hour_chimes = true
quarter_chimes = true
hour_pips = false
cuckoo = false
sound_volume = 25

[EVENTS]
stage1Days = 5
stage2Days = 10
stage3Days = 30
stage1Colour = "red"
stage2Colour = "yellow"
stage3Colour = "green"
nowColour = "blue"
