#   Configure file for pyKlock.py 
#   (c) Kevin Scott   Written Monday 08 December 2025  22:16:59
#
#   true and false are lower case 
#
[INFO]
myVERSION = "2025.11"
myNAME = "pyKlock"

[APPLICATION]
x_pos = 2471
y_pos = 28
width = 920
height = 189
confirmExit = false

[DISPLAY]
foreground = "#aa0000"
background = "#000000"
transparent = true

[TIME]
mode = "Text"
format = "Fuzzy Time"
font = "Edwardian Script ITC,72,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,Regular"
