#   Configure file for pyKlock.py 
#   (c) Kevin Scott   Written Monday 22 December 2025  20:12:43
#
#   true and false are lower case 
#
[INFO]
myNAME = "pyKlock"
myVERSION = "2025.17"

[APPLICATION]
x_pos = 2451
y_pos = 1
width = 1041
height = 91
confirmExit = false

[DISPLAY]
foreground = "#ffff00"
background = "#000000"
transparent = true

[TIME]
mode = "Text"
format = "Time in Words"
font = "Toy Train,28,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,Regular"
alignment = "Right"
prefix = "*"
postfix = ""
space = "{"
