#   Configure file for pyKlock.py 
#   (c) Kevin Scott   Written Friday 12 December 2025  21:29:32
#
#   true and false are lower case 
#
[INFO]
myVERSION = "2025.15"
myNAME = "pyKlock"

[APPLICATION]
x_pos = 2486
y_pos = 7
width = 753
height = 154
confirmExit = false

[DISPLAY]
foreground = "#ff55ff"
background = "#000000"
transparent = true

[TIME]
mode = "Text"
format = "Fuzzy Time"
font = "Edwardian Script ITC,72,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,Regular"
alignment = "Right"
