#   Configure file for pyKlock.py 
#   (c) Kevin Scott   Written Friday 05 December 2025  21:17:07
#
#   true and false are lower case 
#
[INFO]
myVERSION = "2025.8"
myNAME = "pyKlock"

[APPLICATION]
x_pos = 2712
y_pos = 419
width = 713
height = 200
confirmExit = false

[DISPLAY]
foreground = "#00ff00"
background = "#000000"
transparent = true

[TIME]
mode = "Text"
format = "Fuzzy Time"
font = "Curlz MT,36,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,Regular"
