#   Configure file for pyKlock.py 
#   (c) Kevin Scott   Written Friday 23 January 2026  21:55:54
#
#   true and false are lower case 
#
[INFO]
myNAME = "pyKlock"
myVERSION = "2026.35"

[APPLICATION]
x_pos = 3012
y_pos = 30
width = 580
height = 58
confirmExit = false
menuBar = true
toolBar = false

[DISPLAY]
foreground = "#ffaa00"
background = "#000000"
transparent = true
infoLine = true

[TIME]
mode = "Text"
format = "Fuzzy Time"
font = "Vladimir Script,36,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,Regular"
alignment = "Right"
prefix = ""
postfix = ""
space = " "

[SOUNDS]
sounds = true
westminster = true
hour_chimes = true
quarter_chimes = true
hour_pips = false
cuckoo = false
sound_volume = 52
