#   Configure file for pyKlock.py 
#   (c) Kevin Scott   Written Friday 12 December 2025  19:40:36
#
#   true and false are lower case 
#
[INFO]
myVERSION = "2025.14"
myNAME = "pyKlock"

[APPLICATION]
x_pos = 2534
y_pos = 15
width = 920
height = 189
confirmExit = false

[DISPLAY]
foreground = "#ff55ff"
background = "#000000"
transparent = true

[TIME]
mode = "Text"
format = "Fuzzy Time"
font = "Edwardian Script ITC,72,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,Regular"
