#   Configure file for pyKlock.py 
#   (c) Kevin Scott   Written Tuesday 30 December 2025  22:21:34
#
#   true and false are lower case 
#
[INFO]
myNAME = "pyKlock"
myVERSION = "2025.21"

[APPLICATION]
x_pos = 100
y_pos = 100
width = 489
height = 98
confirmExit = false

[DISPLAY]
foreground = "#ffff00"
background = "#000000"
transparent = true
infoLine = true

[TIME]
mode = "Text"
format = "Fuzzy Time"
font = "Vladimir Script,36,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,Regular"
alignment = "Right"
prefix = ""
postfix = ""
space = " "
