#   Configure file for pyKlock.py 
#   (c) Kevin Scott   Written Thursday 19 February 2026  19:52:26
#
#   true and false are lower case 
#
[INFO]
myVERSION = "2026.44"
myNAME = "pyKlock"

[APPLICATION]
x_pos = 2882
y_pos = 45
width = 473
height = 0
confirmExit = false
menu = true
toolBar = false
menuBar = true

[DISPLAY]
foreground = "#00ff00"
background = "#000000"
transparent = true
infoLine = true

[TIME]
mode = "Text"
format = "Fuzzy Time"
font = "Chiller,48,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,Regular"
alignment = "Right"
prefix = ""
postfix = ""
space = " "

[SOUNDS]
sounds = true
westminster = true
hour_chimes = true
quarter_chimes = true
hour_pips = false
cuckoo = false
sound_volume = 12

[EVENTS]
stage1Days = 5
stage2Days = 10
stage3Days = 30
stage1Colour = "red"
stage2Colour = "yellow"
stage3Colour = "green"
nowColour = "blue"
