#   Configure file for pyKlock.py 
#   (c) Kevin Scott   Written Thursday 11 December 2025  15:20:03
#
#   true and false are lower case 
#
[INFO]
myVERSION = "2025.13"
myNAME = "pyKlock"

[APPLICATION]
x_pos = 2499
y_pos = 9
width = 920
height = 189
confirmExit = false

[DISPLAY]
foreground = "#ff55ff"
background = "#000000"
transparent = true

[TIME]
mode = "Text"
format = "Fuzzy Time"
font = "Edwardian Script ITC,72,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,Regular"
