#   Configure file for pyKlock.py 
#   (c) Kevin Scott   Written Wednesday 24 December 2025  14:17:02
#
#   true and false are lower case 
#
[INFO]
myNAME = "pyKlock"
myVERSION = "2025.18"

[APPLICATION]
x_pos = 2460
y_pos = 1
width = 916
height = 91
confirmExit = false

[DISPLAY]
foreground = "#ffff00"
background = "#000000"
transparent = true

[TIME]
mode = "Text"
format = "Fuzzy Time"
font = "Toy Train,28,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,Regular"
alignment = "Right"
prefix = "*"
postfix = ""
space = "{"
